apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
spec:
  rules:
  - host: api.streamify.local
    http:
      paths:
      - path: /api/auth
        pathType: Prefix
        backend:
          service:
            name: {{ .Chart.Name }}-auth
            port:
              number: 8000
