apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Values.services.auth.name }}
spec:
  selector:
    app: {{ .Chart.Name }}-{{ .Values.services.auth.name }}
  ports:
  - port: {{ .Values.services.auth.port }}
    targetPort: {{ .Values.services.auth.port }}
