global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8000']

  - job_name: 'stream-service'
    static_configs:
      - targets: ['stream-service:8000']

  - job_name: 'chat-service'
    static_configs:
      - targets: ['chat-service:8000']

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8000']
